#!/usr/bin/env bash

################################################################################
#                                                                              #
#                                                                              #
#                               pacmanToolBelt                                 #
#                                                                              #
# Created By: S4NDM4N                                           Version: 0.0.1 #
################################################################################

#To echo the messages
printLine(){ echo "@" >&2 ; }

#Sources in  eos-shared and checks for the shared script.
commonScriptCehck(){
    
    local LIB_EOS_SCRIPT=source /usr/share/endeavouros/scripts/eos-script-lib-yad

    if [ ! -f $LIB_EOS_SCRIPT ] ; then
        printLine "Please installe 'eos-bash-share' for this script to work."
        exit 1
    fi

    #Imports in all the goodness from the eos-shared lib.
    source $LIB_EOS_SCRIPT

    #export the needed functions.
    #export -f eos_yad
    export -f eos_yab_RunCmdTermBash
    export -f eos_yad_teminal

}

#Check su or sudo available.
sudoCheck(){
    
    local chkSudo
    local chkSu

    chkSudo=$(sudo -nv 2>&1)
    chkSu=$(su -nv 2>&1)

    if echo "$chkSudo" | grep -q '^sudo:'; then
        echo "sudo"
    elif echo "$chkSu" | grep -q '^su:'; then
        echo "su"
    else
        echo "non"
    fi

}

#After checking echos the right one and assignes the right one the variable.
setSudo(){
    
    suChk=$(sudoCheck)

    case "$suChk" in
        "sudo") echo "sudo" ;;
        "su") echo "su" ;;
        *) exit 1  ;;
    esac
}

#Creating the UI using YAD.
mainFunstionSet(){

#Text for the UI.
local lbl=""
lbl+="Wlecome to pacmanToolBelt\n"
lbl+="This is simple <b>UI</b> for pacman. It runs some simple commen commands\n"
lbl+="with out typing in the terminal.\n"

local windowContent=(
    yad --form --align-buttons --use-interp --title="Pacman Tool Belt"
    --text="$lbl" --image=gtk-convert --window-icon=gtk-convert --columns=2
)

    windowContent+=(
        --field="Update!application-internet!Synchronize the databases":fbtn "RunInTerminal setSudo pacman -Sy"
    )

    windowContent+=(
        --field="Update!application-system!Synchronize the databases and install updates":fbtn "RunInTerminal setSudo pacman -Syu"
    )

    windowContent+=(
        --field="Update!preferences-system!Search for the software in te repos":fbtn 'enterSoftwareName'
    )

    windowContent+=(
        --field="Update!preferences-system!Search for installed software details":fbtn 'enterSoftwareName'
    )

}